name: smude
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - numpy=1.19.1
  - opencv=4.4.0
  - openh264=2.1.0
  - python=3.8.5
  - pytorch=1.6.0
  - pytorch-lightning=0.9.0
  - scikit-image=0.17.2
  - scipy=1.5.2
  - torchvision=0.7.0
  - typing=3.7.4.3
  - typing_extensions=3.7.4.2
  - tqdm=4.48.2
  - requests=2.24.0